casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 海岸明珠;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 海月花园;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 漾日湾畔;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 碧海天家园;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 缤纷假日豪园;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 蔚蓝海岸;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 金海岸大厦;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 青春家园;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 鸿瑞花园;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 鼎太风华;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 诺德假日;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 中海阳光玫瑰;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 招商名仕;sleep 1
casperjs /home/douglas/pybug/hello-pug/trunk/lianjia/lj.js 信和自由;sleep 1
